# Generated by Django 5.2.8 on 2025-11-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('IT', 'Italian'), ('CH', 'Chinese'), ('MX', 'Mexican'), ('AM', 'American'), ('GR', 'Greek'), ('FF', 'Fast Food'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
